export const MEXICAN_CITIES_BY_STATE: Record<string, string[]> = {
    "Aguascalientes": ["Aguascalientes", "Asientos", "Calvillo", "Cosío", "Jesús María", "Pabellón de Arteaga", "Rincón de Romos", "San Francisco de los Romo", "San José de Gracia", "Tepezalá", "El Llano"],
    "Baja California": ["Ensenada", "Mexicali", "Playas de Rosarito", "Tecate", "Tijuana", "San Quintín"],
    "Baja California Sur": ["Comondú", "Mulegé", "La Paz", "Los Cabos", "Loreto"],
    "Campeche": ["Campeche", "Carmen", "Champotón", "Hecelchakán", "Hopelchén", "Palizada", "Tenabo", "Escárcega", "Calakmul", "Candelaria", "Dzitbalché"],
    "Coahuila": ["Abasolo", "Acuña", "Allende", "Arteaga", "Candela", "Castaños", "Cuatro Ciénegas", "Escobedo", "Francisco I. Madero", "Frontera", "General Cepeda", "Guerrero", "Hidalgo", "Jiménez", "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", "Ramos Arizpe", "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", "San Juan de Sabinas", "San Pedro", "Sierra Mojada", "Torreón", "Viesca", "Villa Unión", "Zaragoza"],
    "Colima": ["Armería", "Colima", "Comala", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Manzanillo", "Minatitlán", "Tecomán", "Villa de Álvarez"],
    "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán de Domínguez", "Ocosingo", "Chiapa de Corzo", "Palenque", "Villaflores", "Cintalapa", "Reforma"],
    "Chihuahua": ["Chihuahua", "Juárez", "Cuauhtémoc", "Delicias", "Hidalgo del Parral", "Nuevo Casas Grandes", "Camargo", "Meoqui", "Jiménez", "Guerrero"],
    "Ciudad de México": ["Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuajimalpa de Morelos", "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "La Magdalena Contreras", "Miguel Hidalgo", "Milpa Alta", "Tláhuac", "Tlalpan", "Venustiano Carranza", "Xochimilco"],
    "Durango": ["Durango", "Gómez Palacio", "Lerdo", "Pueblo Nuevo", "Santiago Papasquiaro", "Guadalupe Victoria", "Canatlán", "Cuencamé", "Vicente Guerrero", "Mezquital"],
    "Guanajuato": ["León", "Irapuato", "Celaya", "Salamanca", "Silao de la Victoria", "Guanajuato", "San Miguel de Allende", "Dolores Hidalgo Cuna de la Independencia Nacional", "Valle de Santiago", "Acámbaro"],
    "Guerrero": ["Acapulco de Juárez", "Chilpancingo de los Bravo", "Iguala de la Independencia", "Zihuatanejo de Azueta", "Taxco de Alarcón", "Chilapa de Álvarez", "Tlapa de Comonfort", "Ometepec", "Pungarabato", "Tixtla de Guerrero"],
    "Hidalgo": ["Pachuca de Soto", "Mineral de la Reforma", "Tulancingo de Bravo", "Tula de Allende", "Huejutla de Reyes", "Tizayuca", "Ixmiquilpan", "Tepeji del Río de Ocampo", "Actopan", "Zimapán"],
    "Jalisco": ["Guadalajara", "Zapopan", "San Pedro Tlaquepaque", "Tlajomulco de Zúñiga", "Tonalá", "Puerto Vallarta", "Lagos de Moreno", "Tepatitlán de Morelos", "Zapotlán el Grande", "El Salto"],
    "México": ["Ecatepec de Morelos", "Nezahualcóyotl", "Toluca", "Naucalpan de Juárez", "Chimalhuacán", "Tlalnepantla de Baz", "Cuautitlán Izcalli", "Atizapán de Zaragoza", "Ixtapaluca", "Tecámac"],
    "Michoacán": ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Zitácuaro", "Apatzingán", "La Piedad", "Sahuayo", "Maravatío", "Tacámbaro"],
    "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec", "Emiliano Zapata", "Ayala", "Xochitepec", "Puente de Ixtla", "Jojutla"],
    "Nayarit": ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla", "Compostela", "Xalisco", "Tecoala", "Acaponeta", "Ruiz", "San Blas", "Rosamorada"],
    "Nuevo León": ["Monterrey", "Guadalupe", "Apodaca", "San Nicolás de los Garza", "General Escobedo", "Santa Catarina", "Juárez", "García", "San Pedro Garza García", "Cadereyta Jiménez"],
    "Oaxaca": ["Oaxaca de Juárez", "San Juan Bautista Tuxtepec", "Salina Cruz", "Juchitán de Zaragoza", "Santa Cruz Xoxocotlán", "Huajuapan de León", "Santo Domingo Tehuantepec", "San Pedro Mixtepec", "Puerto Escondido", "Miahuatlán de Porfirio Díaz"],
    "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "San Pedro Cholula", "Cuautlancingo", "Amozoc", "San Andrés Cholula", "Huauchinango", "Zacatlán"],
    "Querétaro": ["Querétaro", "San Juan del Río", "El Marqués", "Corregidora", "Pedro Escobedo", "Cadereyta de Montes", "Amelaco de Bonfil", "Tequeisquiapan", "Colón", "Tolimán"],
    "Quintana Roo": ["Benito Juárez", "Solidaridad", "Othón P. Blanco", "Cozumel", "Felipe Carrillo Puerto", "Tulum", "Bacalar", "Isla Mujeres", "José María Morelos", "Lázaro Cárdenas"],
    "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala", "Rioverde", "Tamazunchale", "Mexquitic de Carmona", "Ciudad Fernández", "Xilitla", "Ebano"],
    "Sinaloa": ["Culiacán", "Mazatlán", "Ahome", "Guasave", "Navolato", "Salvador Alvarado", "El Fuerte", "Escuinapa", "Rosario", "Angostura"],
    "Sonora": ["Hermosillo", "Cajeme", "Nogales", "San Luis Río Colorado", "Navojoa", "Guaymas", "Caborca", "Puerto Peñasco", "Etchojoa", "Agua Prieta"],
    "Tabasco": ["Centro", "Cárdenas", "Comalcalco", "Huimanguillo", "Macuspana", "Cunduacán", "Nacajuca", "Paraíso", "Jalpa de Méndez", "Tenosique"],
    "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Ciudad Victoria", "Altamira", "Ciudad Madero", "El Mante", "Río Bravo", "Valle Hermoso"],
    "Tlaxcala": ["Tlaxcala", "Huamantla", "Apizaco", "San Pablo del Monte", "Chiautempan", "Calpulalpan", "Zacatelco", "Contla de Juan Cuamatzi", "Tetla de la Solidaridad", "Tlaxco"],
    "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica de Hidalgo", "Orizaba", "Minatitlán", "Tuxpan", "Boca del Río", "Pánuco"],
    "Yucatán": ["Mérida", "Kanasín", "Valladolid", "Tizimín", "Umán", "Progreso", "Tekax", "Ticul", "Motul", "Hunucmá", "Izamal", "Maxcanú"],
    "Zacatecas": ["Zacatecas", "Fresnillo", "Guadalupe", "Jerez", "Río Grande", "Sombrerete", "Calera", "Morelos", "Loreto", "Ojocaliente"]
};
